import type { EvidenceSourceDefinition } from "@pro-flow/career-core";

export const executiveEvidenceSources = [
  {
    id: "professional_genome",
    relativePath: "career_os/knowledge/professional_genome.md",
    label: "Professional genome",
    kind: "knowledge",
    targetPath: "positioning",
  },
  {
    id: "verified_career_history",
    relativePath: "career_os/knowledge/verified_career_history.md",
    label: "Verified career history",
    kind: "knowledge",
    targetPath: "careerHistory",
  },
  {
    id: "biography",
    relativePath: "career_os/knowledge/biography.md",
    label: "Biography",
    kind: "knowledge",
    targetPath: "positioning.biography",
  },
  {
    id: "skills",
    relativePath: "career_os/knowledge/skills.md",
    label: "Verified skills",
    kind: "knowledge",
    targetPath: "skills",
  },
  {
    id: "education_credentials",
    relativePath: "career_os/knowledge/education_credentials.md",
    label: "Education and credentials",
    kind: "knowledge",
    targetPath: "education",
  },
  {
    id: "approved_metrics",
    relativePath: "career_os/knowledge/approved_metrics.md",
    label: "Approved metrics",
    kind: "knowledge",
    targetPath: "metrics",
  },
  {
    id: "voice_profile",
    relativePath: "career_os/knowledge/voice_profile.md",
    label: "Voice profile",
    kind: "knowledge",
    targetPath: "voiceRules",
  },
  {
    id: "prohibited_claims",
    relativePath: "career_os/knowledge/prohibited_claims.md",
    label: "Prohibited claims",
    kind: "knowledge",
    targetPath: "prohibitedClaims",
  },
  {
    id: "shrine_ops",
    relativePath: "career_os/projects/shrine_ops.md",
    label: "Shrine Ops",
    kind: "project",
    targetPath: "projects",
  },
  {
    id: "hireflow_ai",
    relativePath: "career_os/projects/hireflow_ai.md",
    label: "HireFlow AI",
    kind: "project",
    targetPath: "projects",
  },
  {
    id: "podcast_automation",
    relativePath: "career_os/projects/podcast_automation.md",
    label: "Podcast automation",
    kind: "project",
    targetPath: "projects",
  },
  {
    id: "sustainability_net_zero",
    relativePath: "career_os/projects/sustainability_net_zero.md",
    label: "Sustainability and Net Zero",
    kind: "project",
    targetPath: "projects",
  },
] as const satisfies readonly EvidenceSourceDefinition[];
